### ISSUE TITLE
index.html receives an empty revision hash

### ISSUE THREAD

**Issue by duizendnegen** [dschmidt/ember-cli-deploy-sentry#10]
From #9 

It looks like in the newer version of `revision-data` data get inserted in `prepare`; in earlier versions it attached the revision data in `didBuild`. (See https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/commit/f53a9829e6af591dba95648a7c5ce4e58aa72578)
@dschmidt shall we put the index.html editing in `didPrepare`? With `prepare` we had to make sure in a way (in `package.json`?) that it got loaded _after_ `revision-data` - this was the short discussion that we had in #5.

**Comment by dschmidt** [comment]
Sure, don't see why it would be bad...
