### ISSUE TITLE
Push a new release

### ISSUE THREAD

**Issue by orf** [dschmidt/ember-cli-deploy-sentry#15]
Hey there, is it possible to push a new release to `npm`?

**Comment by dschmidt** [comment]
Yes, was planning to do that the other day actually. Will try to get to it tomorrow.

**Comment by dschmidt** [comment]
Done, can you confirm it works as expected? Haven't had a chance to test

**Comment by dschmidt** [comment]
No complaints yet, closing

**Comment by orf** [comment]
Oh sorry, I forgot to reply! Yeah it works great, we've done a lot of
deploys and not seen a single failure. Thanks!
