### ISSUE TITLE
Only upload JavaScript files and corresponding source maps

### ISSUE THREAD

**Issue by Turbo87** [dschmidt/ember-cli-deploy-sentry#24]
The addon currently seems to upload **all** files in the `dist` folder, but for sentry to work properly we only need to upload the JavaScript files and corresponding source maps. I guess we should add some sort of filter on the file extensions.

**Comment by dschmidt** [comment]
Sounds good

**Comment by dschmidt** [comment]
Actually ... that's what the `filePattern` config option should do.
https://github.com/dschmidt/ember-cli-deploy-sentry#filepattern

Doesn't that work?

**Comment by Turbo87** [comment]
> Doesn't that work?

hmm... now that you say it... I can't remember overwriting that option so it should have used the default, but I still got a lot of other files uploaded as well.

**Comment by dschmidt** [comment]
What's the state of this?

**Comment by Turbo87** [comment]
I don't remember 😞
