### ISSUE TITLE
Ability to disable in `config/deploy.js`

### ISSUE THREAD

**Issue by melv-n** [dschmidt/ember-cli-deploy-sentry#37]
It would be fantastic if we could disable deploying to sentry in specific situations (such as local deploys/debugging). I've tried unsetting `ENV.sentry` but it will throw an exception for each missing property, making it impossible to easily disable this behaviour (and as a result littering our releases on the Sentry Dashboard).

Being able to unset `ENV.sentry` would be one way, or introducing a simple `ENV.sentry.enabled` flag which defaults to `true` but can be set to `false` to prevent running the plugin.

Thoughts?

**Comment by duizendnegen** [comment]
Absolutely! http://ember-cli-deploy.com/docs/v1.0.x/configuration/#advanced-plugin-configuration - section "Disabling Plugins", this should solve this case. Closing this, feel free to re-open if I misunderstood.

**Comment by melv-n** [comment]
@duizendnegen That does exactly what I need, and thanks for the extremely swift reply 👍 x 1009!
