### ISSUE TITLE
I get sourcemaps in sentry without this addon. Why would I need this addon to upload them? Does it do anything other than upload sourcemaps?

### ISSUE THREAD

**Issue by devinrhode2** [dschmidt/ember-cli-deploy-sentry#44]
I setup ember-cli-sentry, and tested throwing an error, and it works, with sourcemaps. I saw in the docs for that addon that mentioned something about adding `sourcemaps: true`.

Here's the thing: everything works, sentry is getting sourcemaps just by setting `sourcemaps: true`, this addon states it "uploads sourcemaps to sentry" but I don't see why that is necessary right now. Maybe sentry added a feature where it reads the sourcemap url from the javascript and then grabs that itself.. but I haven't put anything on a public server, and I know it can't just read the sourcemap off my local server..

I haven't tested if doing a prod build of ember and seeing if a manually thrown error still appears in sentry.

Does this addon do anything other than upload sourcemaps to sentry? It would probably be great for notifying sentry of releases (https://docs.sentry.io/learn/releases/?_ga=2.81390295.1321994106.1516215236-590692524.1516215236)

**Comment by devinrhode2** [comment]
looks like when I do an `ember build -prod` and manually throw, the function names are minified, so I think I will need this addon

**Comment by devinrhode2** [comment]
Should add to the description at the top "and tags releases for sentry to track when fixes are deployed and close issues in sentry"

**Comment by devinrhode2** [comment]
Just to be clear does the `enableRevisionTagging` key mean that this release tagging feature will be used? https://docs.sentry.io/learn/releases/?_ga=2.81390295.1321994106.1516215236-590692524.1516215236 Which means you also need to https://sentry.io/organizations/alliance-laundry-systems/repos/ and setup this release tracking feature right?

**Comment by duizendnegen** [comment]
Yep - the sourcemaps are meant for minified function names. Either you upload the sourcemaps to your asset target (which enables others to also un-minify your source code), or 'privately' to Sentry. That's what this feature is about.

About the revision tagging: this is meant to target the release tagging feature. No other setup _should_ be required (but it's been more than 2 years since I've done this, so things might have changed).

I'm closing this issue, feel free to keep asking questions & I'll do my best to respond - otherwise I'd recommend opening a question on Stackoverflow :)

**Comment by devinrhode2** [comment]
SO is great for SEO so I'll move this there to give you some points! :)

**Comment by devinrhode2** [comment]
Here's a new one for now, I created a tag for "ember-cli-sentry" for this actually https://stackoverflow.com/questions/48329217/emberhook-to-execute-code-after-model-loads-from-any-route

**Comment by devinrhode2** [comment]
Hate to bug you again but I've found the docs for ember-cli-sentry a bit confusing, and described that quite a bit here if you are interested in helping to clarify the docs a little bit: https://github.com/damiencaselli/ember-cli-sentry/issues/114
