### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by kturney** [dschmidt/ember-cli-deploy-sentry#53]
Hi Dominik, any way we can get a release with the fixes currently in master?

Thanks for the addon!

**Comment by dschmidt** [comment]
Yes, sure! Will try to get to it tomorrow!

**Comment by jheth** [comment]
@dschmidt I'd also like a new release 👍

**Comment by dschmidt** [comment]
Aaaand ... it's done ;-)

Sorry, for the delay.
