### ISSUE TITLE
Associate commits with a release

### ISSUE THREAD

**Issue by patocallaghan** [dschmidt/ember-cli-deploy-sentry#61]
Apologies if this is already possible but I couldn't easily find the information how to do it.

We're looking to associate our releases with a specific Git commit. See the Sentry documentation [here](https://docs.sentry.io/workflow/releases/?_ga=2.113345859.514573203.1554973009-355634380.1547487555%3F_ga&platform=browser#associate-commits-with-a-release) on how to do it.

If you were using Sentry CLI you'd do something like the following to associate your release with a commit (where `$VERSION` is the `revisionKey`).

```
sentry-cli releases set-commits --auto $VERSION
```

Is it possible to do this with ember-cli-deploy-sentry? If not any suggestions how to add this functionality? I'd be interested in adding it if it's something you're interested in having.

**Comment by dschmidt** [comment]
To be honest I haven't used this plugin in a long time and I'm not 100% there is or there is no way to achieve this. But at least it's not documented in any way so I tend to think it's not.

It sounds like a nice addition, patch would be appreciated certainly!

**Comment by patocallaghan** [comment]
@dschmidt Cool, thanks. Yep I'll see if I can put together something for this 👍
