### ISSUE TITLE
Not able to handle an existing release with existing artifacts

### ISSUE THREAD

**Issue by timjcook** [dschmidt/ember-cli-deploy-sentry#73]
### Issue
When I try to deploy a certain version multiple times I am getting the following error:
```
StatusCodeError: 409 - {"detail":"A file matching this name already exists for the given release"}
```
because artifacts already are associated with that release.

I also get the following error log
```
SilentError: Creating release failed
```

Looking through the source code it looks to me like this should be handled in `handleExistingRelease` but looking at the logs it doesn't seem to be following that code path in the instances that it fails.

It leads me to suspect that something in `doesReleaseExist` is throwing an exception when it should be returning a `200`. 

My ideal solution in this case the one described in `handleExistingRelease` where we delete all the existing artifacts and upload new ones.

I'm on `v0.7.0` and in cases where a release doesn't already exist, deploying creates one and uploads artifacts fine.

**Comment by dschmidt** [comment]
Thanks for your report!

Sounds good, would you like to give implementing it a shot?

**Comment by timjcook** [comment]
Sure thing. I'll get back to you.

**Comment by veelci** [comment]
@timjcook, I have a PR out that may address the error you are encountering.
